Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tollef/Library/Python/3.11/lib/python/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tollef/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tollef/Library/Python/3.11/lib/python/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/tollef/Library/Python/3.11/lib/python/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tollef/Library/Python/3.11/lib/python/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import ollama

model = "hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF:Q6_K_L"
print(ollama.show(model).modelinfo)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectError[0m                              Traceback (most recent call last)
File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py:69[0m, in [0;36mmap_httpcore_exceptions[0;34m()[0m
[1;32m     68[0m [38;5;28;01mtry[39;00m:
[0;32m---> 69[0m     [38;5;28;01myield[39;00m
[1;32m     70[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py:233[0m, in [0;36mHTTPTransport.handle_request[0;34m(self, request)[0m
[1;32m    232[0m [38;5;28;01mwith[39;00m map_httpcore_exceptions():
[0;32m--> 233[0m     resp [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_pool[49m[38;5;241;43m.[39;49m[43mhandle_request[49m[43m([49m[43mreq[49m[43m)[49m
[1;32m    235[0m [38;5;28;01massert[39;00m [38;5;28misinstance[39m(resp[38;5;241m.[39mstream, typing[38;5;241m.[39mIterable)

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py:216[0m, in [0;36mConnectionPool.handle_request[0;34m(self, request)[0m
[1;32m    215[0m     [38;5;28mself[39m[38;5;241m.[39m_close_connections(closing)
[0;32m--> 216[0m     [38;5;28;01mraise[39;00m exc [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m
[1;32m    218[0m [38;5;66;03m# Return the response. Note that in this case we still have to manage[39;00m
[1;32m    219[0m [38;5;66;03m# the point at which the response is closed.[39;00m

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py:196[0m, in [0;36mConnectionPool.handle_request[0;34m(self, request)[0m
[1;32m    194[0m [38;5;28;01mtry[39;00m:
[1;32m    195[0m     [38;5;66;03m# Send the request on the assigned connection.[39;00m
[0;32m--> 196[0m     response [38;5;241m=[39m [43mconnection[49m[38;5;241;43m.[39;49m[43mhandle_request[49m[43m([49m
[1;32m    197[0m [43m        [49m[43mpool_request[49m[38;5;241;43m.[39;49m[43mrequest[49m
[1;32m    198[0m [43m    [49m[43m)[49m
[1;32m    199[0m [38;5;28;01mexcept[39;00m ConnectionNotAvailable:
[1;32m    200[0m     [38;5;66;03m# In some cases a connection may initially be available to[39;00m
[1;32m    201[0m     [38;5;66;03m# handle a request, but then become unavailable.[39;00m
[1;32m    202[0m     [38;5;66;03m#[39;00m
[1;32m    203[0m     [38;5;66;03m# In this case we clear the connection and try again.[39;00m

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_sync/connection.py:99[0m, in [0;36mHTTPConnection.handle_request[0;34m(self, request)[0m
[1;32m     98[0m     [38;5;28mself[39m[38;5;241m.[39m_connect_failed [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m---> 99[0m     [38;5;28;01mraise[39;00m exc
[1;32m    101[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_connection[38;5;241m.[39mhandle_request(request)

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_sync/connection.py:76[0m, in [0;36mHTTPConnection.handle_request[0;34m(self, request)[0m
[1;32m     75[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 76[0m     stream [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connect[49m[43m([49m[43mrequest[49m[43m)[49m
[1;32m     78[0m     ssl_object [38;5;241m=[39m stream[38;5;241m.[39mget_extra_info([38;5;124m"[39m[38;5;124mssl_object[39m[38;5;124m"[39m)

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_sync/connection.py:122[0m, in [0;36mHTTPConnection._connect[0;34m(self, request)[0m
[1;32m    121[0m [38;5;28;01mwith[39;00m Trace([38;5;124m"[39m[38;5;124mconnect_tcp[39m[38;5;124m"[39m, logger, request, kwargs) [38;5;28;01mas[39;00m trace:
[0;32m--> 122[0m     stream [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_network_backend[49m[38;5;241;43m.[39;49m[43mconnect_tcp[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    123[0m     trace[38;5;241m.[39mreturn_value [38;5;241m=[39m stream

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_backends/sync.py:205[0m, in [0;36mSyncBackend.connect_tcp[0;34m(self, host, port, timeout, local_address, socket_options)[0m
[1;32m    200[0m exc_map: ExceptionMapping [38;5;241m=[39m {
[1;32m    201[0m     socket[38;5;241m.[39mtimeout: ConnectTimeout,
[1;32m    202[0m     [38;5;167;01mOSError[39;00m: ConnectError,
[1;32m    203[0m }
[0;32m--> 205[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mmap_exceptions[49m[43m([49m[43mexc_map[49m[43m)[49m[43m:[49m
[1;32m    206[0m [43m    [49m[43msock[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43msocket[49m[38;5;241;43m.[39;49m[43mcreate_connection[49m[43m([49m
[1;32m    207[0m [43m        [49m[43maddress[49m[43m,[49m
[1;32m    208[0m [43m        [49m[43mtimeout[49m[43m,[49m
[1;32m    209[0m [43m        [49m[43msource_address[49m[38;5;241;43m=[39;49m[43msource_address[49m[43m,[49m
[1;32m    210[0m [43m    [49m[43m)[49m

File [0;32m/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py:158[0m, in [0;36m_GeneratorContextManager.__exit__[0;34m(self, typ, value, traceback)[0m
[1;32m    157[0m [38;5;28;01mtry[39;00m:
[0;32m--> 158[0m     [38;5;28mself[39m[38;5;241m.[39mgen[38;5;241m.[39mthrow(typ, value, traceback)
[1;32m    159[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m [38;5;28;01mas[39;00m exc:
[1;32m    160[0m     [38;5;66;03m# Suppress StopIteration *unless* it's the same exception that[39;00m
[1;32m    161[0m     [38;5;66;03m# was passed to throw().  This prevents a StopIteration[39;00m
[1;32m    162[0m     [38;5;66;03m# raised inside the "with" statement from being suppressed.[39;00m

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpcore/_exceptions.py:14[0m, in [0;36mmap_exceptions[0;34m(map)[0m
[1;32m     13[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(exc, from_exc):
[0;32m---> 14[0m         [38;5;28;01mraise[39;00m to_exc(exc) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mexc[39;00m
[1;32m     15[0m [38;5;28;01mraise[39;00m

[0;31mConnectError[0m: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

[0;31mConnectError[0m                              Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mollama[39;00m
[1;32m      3[0m model [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhf.co/bartowski/Llama-3.2-1B-Instruct-GGUF:Q6_K_L[39m[38;5;124m"[39m
[0;32m----> 4[0m [38;5;28mprint[39m([43mollama[49m[38;5;241;43m.[39;49m[43mshow[49m[43m([49m[43mmodel[49m[43m)[49m[38;5;241m.[39mmodelinfo)

File [0;32m/opt/homebrew/lib/python3.11/site-packages/ollama/_client.py:598[0m, in [0;36mClient.show[0;34m(self, model)[0m
[1;32m    597[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mshow[39m([38;5;28mself[39m, model: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m ShowResponse:
[0;32m--> 598[0m   [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request[49m[43m([49m
[1;32m    599[0m [43m    [49m[43mShowResponse[49m[43m,[49m
[1;32m    600[0m [43m    [49m[38;5;124;43m'[39;49m[38;5;124;43mPOST[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m    601[0m [43m    [49m[38;5;124;43m'[39;49m[38;5;124;43m/api/show[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m    602[0m [43m    [49m[43mjson[49m[38;5;241;43m=[39;49m[43mShowRequest[49m[43m([49m
[1;32m    603[0m [43m      [49m[43mmodel[49m[38;5;241;43m=[39;49m[43mmodel[49m[43m,[49m
[1;32m    604[0m [43m    [49m[43m)[49m[38;5;241;43m.[39;49m[43mmodel_dump[49m[43m([49m[43mexclude_none[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m[43m,[49m
[1;32m    605[0m [43m  [49m[43m)[49m

File [0;32m/opt/homebrew/lib/python3.11/site-packages/ollama/_client.py:177[0m, in [0;36mClient._request[0;34m(self, cls, stream, *args, **kwargs)[0m
[1;32m    173[0m         [38;5;28;01myield[39;00m [38;5;28mcls[39m([38;5;241m*[39m[38;5;241m*[39mpart)
[1;32m    175[0m   [38;5;28;01mreturn[39;00m inner()
[0;32m--> 177[0m [38;5;28;01mreturn[39;00m [38;5;28mcls[39m([38;5;241m*[39m[38;5;241m*[39m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request_raw[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m[38;5;241m.[39mjson())

File [0;32m/opt/homebrew/lib/python3.11/site-packages/ollama/_client.py:118[0m, in [0;36mClient._request_raw[0;34m(self, *args, **kwargs)[0m
[1;32m    117[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_request_raw[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m--> 118[0m   r [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_client[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    119[0m   [38;5;28;01mtry[39;00m:
[1;32m    120[0m     r[38;5;241m.[39mraise_for_status()

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py:827[0m, in [0;36mClient.request[0;34m(self, method, url, content, data, files, json, params, headers, cookies, auth, follow_redirects, timeout, extensions)[0m
[1;32m    812[0m     warnings[38;5;241m.[39mwarn(message, [38;5;167;01mDeprecationWarning[39;00m)
[1;32m    814[0m request [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mbuild_request(
[1;32m    815[0m     method[38;5;241m=[39mmethod,
[1;32m    816[0m     url[38;5;241m=[39murl,
[0;32m   (...)[0m
[1;32m    825[0m     extensions[38;5;241m=[39mextensions,
[1;32m    826[0m )
[0;32m--> 827[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mrequest[49m[43m,[49m[43m [49m[43mauth[49m[38;5;241;43m=[39;49m[43mauth[49m[43m,[49m[43m [49m[43mfollow_redirects[49m[38;5;241;43m=[39;49m[43mfollow_redirects[49m[43m)[49m

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py:914[0m, in [0;36mClient.send[0;34m(self, request, stream, auth, follow_redirects)[0m
[1;32m    906[0m follow_redirects [38;5;241m=[39m (
[1;32m    907[0m     [38;5;28mself[39m[38;5;241m.[39mfollow_redirects
[1;32m    908[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(follow_redirects, UseClientDefault)
[1;32m    909[0m     [38;5;28;01melse[39;00m follow_redirects
[1;32m    910[0m )
[1;32m    912[0m auth [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_build_request_auth(request, auth)
[0;32m--> 914[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_handling_auth[49m[43m([49m
[1;32m    915[0m [43m    [49m[43mrequest[49m[43m,[49m
[1;32m    916[0m [43m    [49m[43mauth[49m[38;5;241;43m=[39;49m[43mauth[49m[43m,[49m
[1;32m    917[0m [43m    [49m[43mfollow_redirects[49m[38;5;241;43m=[39;49m[43mfollow_redirects[49m[43m,[49m
[1;32m    918[0m [43m    [49m[43mhistory[49m[38;5;241;43m=[39;49m[43m[[49m[43m][49m[43m,[49m
[1;32m    919[0m [43m[49m[43m)[49m
[1;32m    920[0m [38;5;28;01mtry[39;00m:
[1;32m    921[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m stream:

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py:942[0m, in [0;36mClient._send_handling_auth[0;34m(self, request, auth, follow_redirects, history)[0m
[1;32m    939[0m request [38;5;241m=[39m [38;5;28mnext[39m(auth_flow)
[1;32m    941[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m--> 942[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_handling_redirects[49m[43m([49m
[1;32m    943[0m [43m        [49m[43mrequest[49m[43m,[49m
[1;32m    944[0m [43m        [49m[43mfollow_redirects[49m[38;5;241;43m=[39;49m[43mfollow_redirects[49m[43m,[49m
[1;32m    945[0m [43m        [49m[43mhistory[49m[38;5;241;43m=[39;49m[43mhistory[49m[43m,[49m
[1;32m    946[0m [43m    [49m[43m)[49m
[1;32m    947[0m     [38;5;28;01mtry[39;00m:
[1;32m    948[0m         [38;5;28;01mtry[39;00m:

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py:979[0m, in [0;36mClient._send_handling_redirects[0;34m(self, request, follow_redirects, history)[0m
[1;32m    976[0m [38;5;28;01mfor[39;00m hook [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_event_hooks[[38;5;124m"[39m[38;5;124mrequest[39m[38;5;124m"[39m]:
[1;32m    977[0m     hook(request)
[0;32m--> 979[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_single_request[49m[43m([49m[43mrequest[49m[43m)[49m
[1;32m    980[0m [38;5;28;01mtry[39;00m:
[1;32m    981[0m     [38;5;28;01mfor[39;00m hook [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_event_hooks[[38;5;124m"[39m[38;5;124mresponse[39m[38;5;124m"[39m]:

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_client.py:1015[0m, in [0;36mClient._send_single_request[0;34m(self, request)[0m
[1;32m   1010[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m   1011[0m         [38;5;124m"[39m[38;5;124mAttempted to send an async request with a sync Client instance.[39m[38;5;124m"[39m
[1;32m   1012[0m     )
[1;32m   1014[0m [38;5;28;01mwith[39;00m request_context(request[38;5;241m=[39mrequest):
[0;32m-> 1015[0m     response [38;5;241m=[39m [43mtransport[49m[38;5;241;43m.[39;49m[43mhandle_request[49m[43m([49m[43mrequest[49m[43m)[49m
[1;32m   1017[0m [38;5;28;01massert[39;00m [38;5;28misinstance[39m(response[38;5;241m.[39mstream, SyncByteStream)
[1;32m   1019[0m response[38;5;241m.[39mrequest [38;5;241m=[39m request

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py:232[0m, in [0;36mHTTPTransport.handle_request[0;34m(self, request)[0m
[1;32m    218[0m [38;5;28;01massert[39;00m [38;5;28misinstance[39m(request[38;5;241m.[39mstream, SyncByteStream)
[1;32m    220[0m req [38;5;241m=[39m httpcore[38;5;241m.[39mRequest(
[1;32m    221[0m     method[38;5;241m=[39mrequest[38;5;241m.[39mmethod,
[1;32m    222[0m     url[38;5;241m=[39mhttpcore[38;5;241m.[39mURL(
[0;32m   (...)[0m
[1;32m    230[0m     extensions[38;5;241m=[39mrequest[38;5;241m.[39mextensions,
[1;32m    231[0m )
[0;32m--> 232[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mmap_httpcore_exceptions[49m[43m([49m[43m)[49m[43m:[49m
[1;32m    233[0m [43m    [49m[43mresp[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_pool[49m[38;5;241;43m.[39;49m[43mhandle_request[49m[43m([49m[43mreq[49m[43m)[49m
[1;32m    235[0m [38;5;28;01massert[39;00m [38;5;28misinstance[39m(resp[38;5;241m.[39mstream, typing[38;5;241m.[39mIterable)

File [0;32m/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py:158[0m, in [0;36m_GeneratorContextManager.__exit__[0;34m(self, typ, value, traceback)[0m
[1;32m    156[0m     value [38;5;241m=[39m typ()
[1;32m    157[0m [38;5;28;01mtry[39;00m:
[0;32m--> 158[0m     [38;5;28mself[39m[38;5;241m.[39mgen[38;5;241m.[39mthrow(typ, value, traceback)
[1;32m    159[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m [38;5;28;01mas[39;00m exc:
[1;32m    160[0m     [38;5;66;03m# Suppress StopIteration *unless* it's the same exception that[39;00m
[1;32m    161[0m     [38;5;66;03m# was passed to throw().  This prevents a StopIteration[39;00m
[1;32m    162[0m     [38;5;66;03m# raised inside the "with" statement from being suppressed.[39;00m
[1;32m    163[0m     [38;5;28;01mreturn[39;00m exc [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m value

File [0;32m/opt/homebrew/lib/python3.11/site-packages/httpx/_transports/default.py:86[0m, in [0;36mmap_httpcore_exceptions[0;34m()[0m
[1;32m     83[0m     [38;5;28;01mraise[39;00m
[1;32m     85[0m message [38;5;241m=[39m [38;5;28mstr[39m(exc)
[0;32m---> 86[0m [38;5;28;01mraise[39;00m mapped_exc(message) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mexc[39;00m

[0;31mConnectError[0m: [Errno 61] Connection refused
ConnectError: [Errno 61] Connection refused

